[[main]]
    name = "About"
    url = "/about/"
    identifier = "about"
    weight = 1
[[main]]
    name = "Overview"
    url = "/about/technology-overview/"
    parent = "about"
    weight = 1
[[main]]
    name = "The XSF"
    url = "/about/xmpp-standards-foundation/"
    parent = "about"
    weight = 2
[[main]]
    name = "Standards Process"
    url = "/about/standards-process/"
    parent = "about"
    weight = 3
[[main]]
    name = "Specifications"
    url = "/extensions/"
    parent = "about"
    weight = 4
[[main]]
    name = "Compliance Suites"
    url = "/about/compliance-suites/"
    parent = "about"
    weight = 5
[[main]]
    name = "FAQ"
    url = "/about/faq/"
    parent = "about"
    weight = 6
[[main]]
    name = "Myths & Legends"
    url = "/about/myths/"
    parent = "about"
    weight = 7
[[main]]
    name = "Publications"
    url = "/about/publications/"
    parent = "about"
    weight = 8
[[main]]
    name = "History"
    url = "/about/history/"
    parent = "about"
    weight = 9

[[main]]
    name = "Uses"
    url = "/uses/"
    identifier = "uses"
    weight = 2
[[main]]
    name = "Instant Messaging"
    url = "/uses/instant-messaging/"
    parent = "uses"
    weight = 1
[[main]]
    name = "Internet of Things"
    url = "/uses/internet-of-things/"
    parent = "uses"
    weight = 2
[[main]]
    name = "Online Gaming"
    url = "/uses/gaming/"
    parent = "uses"
    weight = 3
[[main]]
    name = "Social"
    url = "/uses/social/"
    parent = "uses"
    weight = 4
[[main]]
    name = "WebRTC"
    url = "/uses/webrtc/"
    parent = "uses"
    weight = 5

[[main]]
    name = "Software"
    url = "/software/"
    identifier = "software"
    weight = 3

[[main]]
    name = "Community"
    url = "/community/"
    identifier = "community"
    weight = 4
[[main]]
    name = "Chat/Logs"
    url = "/community/chat/"
    parent = "community"
    weight = 1
[[main]]
    name = "Mailing Lists"
    url = "/community/mailing-lists/"
    parent = "community"
    weight = 2
[[main]]
    name = "Membership"
    url = "/community/membership/"
    parent = "community"
    weight = 3
[[main]]
    name = "Events"
    url = "/community/events/"
    parent = "community"
    weight = 4
[[main]]
    name = "Security Notices"
    url = "/community/security-notices/"
    parent = "community"
    weight = 5
[[main]]
    name = "Sponsors"
    url = "/community/sponsors/"
    parent = "community"
    weight = 6
[[main]]
    name = "Jobs with XMPP"
    url = "https://xmpp.work/"
    parent = "community"
    weight = 7
[[main]]
    name = "Fiscal Hosting"
    url = "/community/fiscalhost/"
    parent = "community"
    weight = 8
[[main]]
    name = "Office Hours"
    url = "/community/officehours/"
    parent = "community"
    weight = 9
[[main]]
    name = "Google Summer of Code 2023"
    url = "/community/gsoc-2023/"
    parent = "community"
    weight = 10

[[main]]
    name = "Getting Started"
    url = "/getting-started/"
    weight = 5

[[main]]
    name = "Newsletter"
    url = "/newsletter/"
    weight = 6

[[main]]
    name = "Blog"
    url = "/blog/"
    identifier = "blog"
    weight = 7

[[main]]
    name = "Jobs"
    url = "https://xmpp.work"
    weight = 8
